### ISSUE TITLE
@tailrec is also bad

### ISSUE THREAD

**Issue by valtih1978** [scala-ide/scala-worksheet#215] opened 2015-03-19 14:20 UTC
`@tailrec` kills error reporting [likewise unspecified overriding does](https://github.com/scala-ide/scala-worksheet/issues/214#issue-61712696). Once I add this attribute, code stops execuing in worksheet.

```scala
object o2 {
	@tailrec def f {if (false) f}
	1
}
```

Environment is the same.

**Comment by sschaef** [comment] 2015-03-19 17:53
Actually, this is a duplicate of #214. It seems to me that it doesn't matter how you create an error, the only thing that matters is that an error exists and that the worksheet doesn't show it.

**Closed by sschaef** 2015-03-19 17:53 UTC
